version: '3.8'
services:    
  process-image-lambda-builder:
    build:
      context: ./ProcessImageLambda
      dockerfile: src/ProcessImageLambda/Dockerfile
    container_name: process-image-lambda-builder
    volumes:
      - "./image_lambda_build:/image_lambda" 
    command: sh -c "cp /tmp/lambda/* /image_lambda/ && echo Lambda zip copied; ls -la /image_lambda"
    
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - DEBUG=${DEBUG-}
      - LAMBDA_RUNTIME_ENVIRONMENT_TIMEOUT=60
      - SERVICES=dynamodb,s3,lambda
      - PERSISTENCE=/tmp/localstack/data
      - LAMBDA_INIT_USER=root
    volumes:
      - './localstack-init.sh:/etc/localstack/init/ready.d/init-aws.sh'
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./image_lambda_build:/image_lambda"
    depends_on:
      - process-image-lambda-builder
  
  webapi:
    build:
      context: .
      dockerfile: Api/Dockerfile
    container_name: webapi
    ports:
      - "5175:8080"
    depends_on:
      - localstack
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:8080"